#!/bin/bash


A="/var/www/html/admin/scripts/pi-hole/js/index.js"

tput clear
echo
echo "********************* Hello $USER! *********************"
echo
echo "This script changes queries number shown in pihole."
echo "Resetting to default value (10)..."
sudo sed -i 's/\getQuerySources=[0-9][[0-9]\&topClientsBlocked=[0-9][[0-9]/getQuerySources\&topClientsBlocked/' $A
sudo sed -i 's/\getQuerySources=&topClientsBlocked=/getQuerySources\&topClientsBlocked/' $A

echo
read -p "Do you want to continue? (Y/n) " -n 1 -r -s
if [[ $REPLY =~ ^[Nn]$ ]]; then
	echo && echo && exit 1
fi

echo && echo
echo "Please write 'Top Clients (total)' queries number (from 10 to 99):"
read t
if [ "$t" -gt 99 ] || [ "$t" -lt 10 ]; then
	echo "Value not correct!" && echo && exit 1
fi

echo
echo "Please write 'Top Clients (blocked only)' queries number (from 10 to 99):"
read b
if [ "$b" -gt 99 ] || [ "$b" -lt 10 ]; then
	echo "Value not correct!" && echo && exit 1
fi

echo
sudo sed -i 's/\getQuerySources\&topClientsBlocked/getQuerySources='$t'\&topClientsBlocked='$b'/' $A
echo "Now queries number are: $t for total and $b for blocked."
echo "Please refresh pihole web page from your browser!"
echo

exit 0
